import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/about-us',
          '/contact', 
          '/enjoy',
          '/enjoy/',
          '/stay',
          '/stay/',
        ],
        disallow: [
          '/admin',
          '/admin/',
          '/login',
          '/register', 
          '/profile',
          '/checkout',
          '/checkout/',
          '/forgot-password',
          '/forgot-password/',
          '/api/',
          '/temp/',
          '/_next/',
          '/private',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/about-us',
          '/contact',
          '/enjoy',
          '/enjoy/',
          '/stay', 
          '/stay/',
        ],
        disallow: [
          '/admin',
          '/admin/',
          '/login',
          '/register',
          '/profile', 
          '/checkout',
          '/checkout/',
          '/forgot-password',
          '/forgot-password/',
          '/api/',
          '/temp/',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/about-us',
          '/contact',
          '/enjoy',
          '/enjoy/',
          '/stay',
          '/stay/',
        ],
        disallow: [
          '/admin',
          '/admin/',
          '/login',
          '/register',
          '/profile',
          '/checkout', 
          '/checkout/',
          '/forgot-password',
          '/forgot-password/',
          '/api/',
          '/temp/',
        ],
        crawlDelay: 2,
      },
    ],
    sitemap: 'https://divingnest.com/sitemap.xml',
    host: 'https://divingnest.com',
  }
}